//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.TeamHistoryManagement.TeamsBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.TeamHistoryManagement.TeamsBot.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelOption {
            get {
                return ResourceManager.GetString("CancelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple conversations.
        /// </summary>
        internal static string ChannelHistoryOptionAll {
            get {
                return ResourceManager.GetString("ChannelHistoryOptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conversation.
        /// </summary>
        internal static string ChannelHistoryOptionConversation {
            get {
                return ResourceManager.GetString("ChannelHistoryOptionConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click ‘sign in’ so that I can access your conversations.
        /// </summary>
        internal static string DialogAuthCardText {
            get {
                return ResourceManager.GetString("DialogAuthCardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry I can&apos;t authenticate of you. I cancel report downloading process..
        /// </summary>
        internal static string DialogAuthErrorMessage {
            get {
                return ResourceManager.GetString("DialogAuthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’m backing up your conversations now – but it might take a minute or two. When the report is ready,
        ///            I will save it to your OneDrive and send you a message so that you can download it..
        /// </summary>
        internal static string DialogFilePreparingMessage {
            get {
                return ResourceManager.GetString("DialogFilePreparingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of file would you like?.
        /// </summary>
        internal static string DialogFileTypeReportMessage {
            get {
                return ResourceManager.GetString("DialogFileTypeReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I&apos;m a bot designed to help you backup your Microsoft Teams conversations.
        ///            I can capture conversations from any group or channel you’re a member of, as well as your chat conversations.
        ///            If you send me a message, I’ll guide you through the process to download your conversations.
        ///            I’ll ask you a few questions to understand which conversations you want to backup.
        ///            I might need to ask you to log into Office 365 during the process so that I have access to your mess [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DialogHelpMessage {
            get {
                return ResourceManager.GetString("DialogHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I can&apos;t understand format for report file. I cancel report downloading process..
        /// </summary>
        internal static string DialogReportFormatErrorMessage {
            get {
                return ResourceManager.GetString("DialogReportFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your history report file is ready in your OneDrive.
        /// </summary>
        internal static string DialogReportReadyMessage {
            get {
                return ResourceManager.GetString("DialogReportReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like me to backup the messages from this conversation thread only, or from multiple conversations in this channel?.
        /// </summary>
        internal static string DialogReportScopeMessage {
            get {
                return ResourceManager.GetString("DialogReportScopeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog is canceled..
        /// </summary>
        internal static string DialogsCancelledMessage {
            get {
                return ResourceManager.GetString("DialogsCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string DialogSignInButton {
            get {
                return ResourceManager.GetString("DialogSignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to backup your conversations?.
        /// </summary>
        internal static string DialogStartChannelHistoryProcessMessage {
            get {
                return ResourceManager.GetString("DialogStartChannelHistoryProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to backup your chat?.
        /// </summary>
        internal static string DialogStartChatHistoryProcessMessage {
            get {
                return ResourceManager.GetString("DialogStartChatHistoryProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I can&apos;t understand time period. I cancel report downloading process..
        /// </summary>
        internal static string DialogTimePeriodErrorMessage {
            get {
                return ResourceManager.GetString("DialogTimePeriodErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How far back would you like me to look?.
        /// </summary>
        internal static string DialogTimeRangeReportMessage {
            get {
                return ResourceManager.GetString("DialogTimeRangeReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to install.
        /// </summary>
        internal static string InstallBotButtonText {
            get {
                return ResourceManager.GetString("InstallBotButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you haven&apos;t added History Export bot in this chat/team. To be able to extract chat history, you should add the bot in this chat..
        /// </summary>
        internal static string InstallBotMessageText {
            get {
                return ResourceManager.GetString("InstallBotMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to extract from this channel?.
        /// </summary>
        internal static string MessageExtChannelScopeMessage {
            get {
                return ResourceManager.GetString("MessageExtChannelScopeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string MessageExtExtractButton {
            get {
                return ResourceManager.GetString("MessageExtExtractButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’m backing up your conversations now – but it might take a minute or two. When the report is ready,
        ///            I will save it to your OneDrive and send you a message so that you can download it.
        ///            You can close this message now..
        /// </summary>
        internal static string MessageExtFilePreparingMessage {
            get {
                return ResourceManager.GetString("MessageExtFilePreparingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of file would you like?.
        /// </summary>
        internal static string MessageExtFileTypeReportMessage {
            get {
                return ResourceManager.GetString("MessageExtFileTypeReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction parameters.
        /// </summary>
        internal static string MessageExtReportParameters {
            get {
                return ResourceManager.GetString("MessageExtReportParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your history report file is ready in your OneDrive.
        /// </summary>
        internal static string MessageExtReportReadyMessage {
            get {
                return ResourceManager.GetString("MessageExtReportReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string MessageExtSignInTitle {
            get {
                return ResourceManager.GetString("MessageExtSignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How far back would you like me to look?.
        /// </summary>
        internal static string MessageExtTimeRangeReportMessage {
            get {
                return ResourceManager.GetString("MessageExtTimeRangeReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string ReportHtmlFormat {
            get {
                return ResourceManager.GetString("ReportHtmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string ReportJsonFormat {
            get {
                return ResourceManager.GetString("ReportJsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string ReportPdfFormat {
            get {
                return ResourceManager.GetString("ReportPdfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT.
        /// </summary>
        internal static string ReportTextFormat {
            get {
                return ResourceManager.GetString("ReportTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been signed out..
        /// </summary>
        internal static string SignedOutMessage {
            get {
                return ResourceManager.GetString("SignedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOutButtonText {
            get {
                return ResourceManager.GetString("SignOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, it looks like something went wrong..
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string TeamGeneralChannelDefaultTitle {
            get {
                return ResourceManager.GetString("TeamGeneralChannelDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As far back as possible.
        /// </summary>
        internal static string TimePeriodOptionAllTime {
            get {
                return ResourceManager.GetString("TimePeriodOptionAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        internal static string TimePeriodOptionLast7Days {
            get {
                return ResourceManager.GetString("TimePeriodOptionLast7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 24 hours.
        /// </summary>
        internal static string TimePeriodOptionLastDay {
            get {
                return ResourceManager.GetString("TimePeriodOptionLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conversation is not supported..
        /// </summary>
        internal static string UnsupportedConversation {
            get {
                return ResourceManager.GetString("UnsupportedConversation", resourceCulture);
            }
        }
    }
}
